version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: touristdb

    ports:
      - "3307:3306"

    networks:
      - tourist-network

  tourist-app:
    build: .

    container_name: tourist-backend-container

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/touristdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - tourist-network

networks:
  tourist-network: