spring.application.name=TouristBackendApp

#General DB Deatils in order to connect with DB
spring.datasource.url=jdbc:mysql://localhost:3307/touristdb
spring.datasource.username=root
spring.datasource.password=root

#Context path is like a common base URL for all APIs.
server.servlet.context-path=/tourist-app


#These are needed for JPA the first one is mandatory
spring.jpa.hibernate.ddl-auto=update

#To enable lazyloading
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#To show the query
spring.jpa.show-sql=true

#To get the sql query in proper format
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#/Actuator health Checkup
#management.endpoints.web.exposure.include=*
#
#//Exclude any endpoints
#management.endpoints.web.exposure.exclude=env,beans
#
#
#//Shutdown the App 
#management.endpoint.shutdown.enabled=false

#Spring Boot profiles
#spring.profiles.active=dev



